---

- name: Add user account for {{ name  }}
  user: name="{{ name  }}"
        comment="{{ comment  }}"

- name: Create .ssh directory for {{ name  }}
  file: path=~{{ name  }}/.ssh
        state=directory
        owner={{ name  }}
        group={{ name  }}
        mode=0700

- name: Set authorized key for {{ name }}
  authorized_key:
    user: "{{ name }}"
    state: present
    key: "{{ lookup('file', 'keys/{{ name  }}.pub')   }}"
