---

- name: Install dependencies for compiling Ruby
  apt:  package={{ item  }}
        state=present
  update_cache: yes
  with_items:
    - gcc
    - libffi-devel
    - libyaml-devel
    - make
    - openssl-devel
    - readline-devel
    - zlib-devel
    - bzip2
